MainApp/urls.py
from django.urls import path
from .views import *
from InventoryOutput import export_stocktake_csv

urlpatterns = [
    path("register/", register, name="register"),
    path("logout/", logout_request, name="logout"),
    path("login/", login_request, name="login"),
    path("composertest/", composer_test, name="composertest"),
    path("export/", export_stocktake_csv, name='export_stocktake_csv'),
]

TrojanProject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import PartsApp
from PartsApp.views import qr_scan

urlpatterns = [
    path('', qr_scan),
    path('admin/', admin.site.urls),
    path('main/',include('MainApp.urls')),
    path('inventory/',include('PartsApp.urls')),
    path('activities/', include('ActivitiesApp.urls')),
    path('workorders/', include('WorkOrdersApp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

WorkOrdersApp/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path('tasks/', task_list, name='tasks'),
    path('task/addtask/', add_task, name='addtask'),
    path('task/<int:taskid>/', info_task_activities, name='infotaskactivities'),
    path('task/<int:taskid>/addTaskActivity', info_task_activity_include, name='addtaskactivity'),
    # path('task/addTaskActivity', TaskActivityCreate.as_view(), name='addtaskactivity'),
    path('task/deleteactivity/<int:pk>', TaskActivityDelete.as_view(), name='deletetaskactivity'),

    path('task/<int:taskid>/<int:taskactivityid>', info_task_parts, name='infotaskparts'),
    path('task/<int:taskid>/<int:taskactivityid>/includerequired', info_task_part_include, {'increment': False}, name='includerequiredpart'),
    path('task/<int:taskid>/<int:taskactivityid>/includeproduced', info_task_part_include, {'increment': True}, name='includeproducedpart'),
    path('task/<int:taskid>/<int:taskactivityid>/completetaskactivity', complete_task_activity , name='completetaskactivity'),
    # path('workcentre/<str:job>/<str:group>/<str:activity>', info_task_parts, name='infojobparts'),
    path('task/editpartserial/<int:pk>', TaskPartSerialUpdate.as_view(), name='edittaskpart-serial'),
    path('task/editpartrequired/<int:pk>', TaskPartRequiredUpdate.as_view(), name='edittaskpart-required'),
    path('task/editpartcompleted/<int:pk>', TaskPartCompletedUpdate.as_view(), name='edittaskpart-completed'),
    path('task/deletepart/<int:pk>', TaskPartDelete.as_view(), name='deletetaskpart'),
    # path('task/deletepart/<int:pk>', ActivityPartDelete.as_view(), name='deleteactivitypart'),
]

WorkOrdersApp/models.py
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404
from django.db import models
from django.utils import timezone
from simple_history.models import HistoricalRecords
from PartsApp.models import *
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.
from ActivitiesApp.models import GroupModel, ActivityModel, GroupActivityModel, ActivityPartModel
from PartsApp.models import PartModel


class TaskModel(models.Model):
    taskName = models.CharField(max_length=50)
    fleetNumber = models.CharField(max_length=50)
    group = models.ForeignKey(GroupModel, on_delete=models.PROTECT)
    completed = models.BooleanField(default=False)

    
    def userGroupCompleted(self,task):
        completedList = TaskActivityModel.objects.filter(task=task)
        for activity in completedList:
            if not activity.isComplete():
                return False
        task.completed = True
        task.save()
        return True

    def __str__(self):
        # return str(self.taskName) + " - " + str(self.group) + " - " + str(self.completed)
        return str(self.taskName) + " => " + str(self.group)

class TaskActivityModel(models.Model):
    task = models.ForeignKey(TaskModel, on_delete=models.CASCADE)
    activity = models.ForeignKey(ActivityModel, on_delete=models.PROTECT)
    startTime = models.DateTimeField(default=timezone.now)
    finishTime = models.DateTimeField(null=True)

    def isComplete(self):
        completedList = TaskPartsModel.objects.filter(activity=self)
        # completedList = [part for part in completedList if not part.isComplete()]
        for part in completedList:
            if not part.isComplete():
                return False

        return True

    def __str__(self):
        return str(self.activity)


class TaskPartsModel(models.Model):
    activity = models.ForeignKey(TaskActivityModel, on_delete=models.CASCADE, null=True)
    part = models.ForeignKey(PartModel, on_delete=models.PROTECT)
    task = models.ForeignKey(TaskModel, on_delete=models.CASCADE, null=True)
    increment = models.BooleanField()
    quantityRequired = models.IntegerField()
    quantityCompleted = models.IntegerField(default=0)
    user = models.ForeignKey(User, on_delete=models.PROTECT, null=True)
    serial = models.CharField(max_length=50, null=True)
    order = models.IntegerField(blank=False)
    extra = models.CharField(max_length=50, null=True)
    history = HistoricalRecords()

    # @property
    def isComplete(self):
        return self.quantityRequired == self.quantityCompleted

    def updateQuantity(self, newval, user):
        self.user = user
        change = newval-self.quantityCompleted
        print(change)
        if change != 0:
            if self.increment:
                self.part.stockOnHand += change
                # print(change)
            else:
                self.part.stockOnHand -= change
                # print(change)
            self.quantityCompleted = newval
            self.save()

            self.part._change_reason = f'{self.activity}:{change}'
            self.part.save()

            if self.activity.isComplete():
                self.activity.finishTime = timezone.now()
                self.activity.save()

    def __str__(self):
        return str(self.part)

WorkOrdersApp/views.py
from django import http
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.utils import timezone
from django.views.generic import UpdateView, DeleteView, CreateView

from ActivitiesApp.models import GroupActivityModel, ActivityPartModel, ActivityModel, GroupModel, instruction
from PartsApp.models import PartModel
from .forms import TaskForm, TaskActivityPartsForm, TaskActivitiesForm
from .models import TaskModel, TaskPartsModel, TaskActivityModel, PartImageModel
from django.contrib.auth.decorators import login_required


@login_required
def task_list(request):
    activities = ActivityModel.objects.filter(workCenter__in=request.user.groups.all())
    activitytasks = TaskActivityModel.objects.filter(activity__in=activities)
    tasklist = activitytasks.values_list('task',flat=True)
    # tasks = TaskModel.objects.filter(group__in=set(tasklist)).order_by('pk')
    tasks = TaskModel.objects.all()

    
    activeList = []
    completedList = []
    for task in tasks:
        if task.completed == False: #and task.group == request.user.groups.all() :
            activeList += [task]
        else:
            completedList += [task]

    return render(request, 'WorkOrdersApp/listTasks.html', {'header': 'Outstanding Tasks',
                                                            'activetasks': activeList,
                                                            'completedtasks': reversed(completedList)})


@login_required
def add_task(request):
    if request.method == "POST":
        form = TaskForm(request.POST)
        if form.is_valid():

            if TaskModel.objects.filter(taskName=form.cleaned_data['taskName']).count() > 0:
                messages.error(request, "Task already exists")
                return redirect('addtask')

            taskMy = form.save()
            groupname = form.cleaned_data['group']

            groupactivitylist = GroupActivityModel.objects.filter(group=groupname).order_by('order')

            for groupactivity in groupactivitylist:
                tempactivity = TaskActivityModel(task=taskMy,
                                                 activity=groupactivity.activity)
                tempactivity.save()
                required_list = ActivityPartModel.objects.filter(activity=groupactivity.activity).order_by('id')
                for required in required_list:
                    temp = TaskPartsModel(activity=tempactivity,
                                          part=required.part,
                                          task=taskMy,
                                          increment=required.increment,
                                          quantityRequired=required.quantity,
                                          order=required.order,
                                          extra=required.location,
                                          quantityCompleted=0,
                                          )
                    temp.save()

            return redirect('tasks')
    else:
        form = TaskForm()
        groups = GroupModel.objects.all()
        return render(request, 'WorkOrdersApp/addTask.html', {'taskform': form, 'groups': groups})


@login_required
def info_task_activities(request, taskid):
    task = get_object_or_404(TaskModel, id=taskid)
    activities = TaskActivityModel.objects.filter(task=task, activity__workCenter__in=request.user.groups.all())

    # if activities.count() == 1:
    #     activity = activities.first()
    #     return info_task_parts(request, taskid, activity.id)

    for activity in activities:
        activity.complete = activity.isComplete()
        partsRequired = TaskPartsModel.objects.filter(activity=activity)

        completedList = [part for part in partsRequired if not part.isComplete()]

        if len(completedList) > 0:
            activity.status = activity.activity.getStatus()
        else:
            activity.status = "Done"

    return render(request, 'WorkOrdersApp/infoTaskActivities.html', {'header': 'Grouped Activities',
                                                                     'task': task,
                                                                     'taskactivities': activities})


class TaskActivityDelete(DeleteView):
    # http_method_names = ['post']
    model = TaskActivityModel
    fields = "__all__"

    def get_success_url(self):
        return reverse('infotaskactivities', args=[str(self.object.task.pk)])


@login_required
def info_task_parts(request, taskid, taskactivityid):
    taskactivity = get_object_or_404(TaskActivityModel, id=taskactivityid)
    instructions = instruction.objects.filter(activity=taskactivity.activity)

    if request.method == "POST":
        for completed in request.POST:
            try:
                updatedvalue = get_object_or_404(TaskPartsModel, id=int(completed))
                updatedvalue.updateQuantity(int(request.POST[completed]), request.user)
            except ValueError:
                pass

    # activity_part_required = ActivityPartModel.objects.filter(activity=taskactivity.activity, increment=False).order_by('order')
    #
    # activity_part_produced = ActivityPartModel.objects.filter(activity=taskactivity.activity, increment=True).order_by('order')

    taskPartsRequired = TaskPartsModel.objects.filter(task=taskid, activity=taskactivityid, increment=False).order_by('order')
    for part in taskPartsRequired:
        part.thumbnail = PartImageModel.objects.filter(part=part.part).first()
        part.low = part.part.stockOnHand < part.part.minimumStock

    taskPartsProduced = TaskPartsModel.objects.filter(task=taskid, activity=taskactivityid, increment=True).order_by('order')
    for part in taskPartsProduced:
        part.thumbnail = PartImageModel.objects.filter(part=part.part).first()
        part.low = part.part.stockOnHand < part.part.minimumStock

    context = {'header': 'Kits',
               'producedparts': taskPartsProduced,
               'requiredparts': taskPartsRequired,
               'taskid': taskid,
               'taskactivity': taskactivity,
               'instructions': instructions}

    if get_object_or_404(TaskActivityModel, id=taskactivityid).activity.workCenter.name == 'Picking':
        return render(request, 'WorkOrdersApp/infoTaskPickingParts.html', context)

    elif get_object_or_404(TaskActivityModel, id=taskactivityid).activity.workCenter.name == 'Lazer Cutting':
        return render(request, 'WorkOrdersApp/infoTaskLaserCuttingParts.html', context)

    elif get_object_or_404(TaskActivityModel, id=taskactivityid).activity.workCenter.name == 'Powder Coating':
        return render(request, 'WorkOrdersApp/infoTaskPowderCoatingParts.html', context)

    elif get_object_or_404(TaskActivityModel, id=taskactivityid).activity.workCenter.name == 'Zinc Coating':
        return render(request, 'WorkOrdersApp/infoTaskZincCoatingParts.html', context)

    elif get_object_or_404(TaskActivityModel,
                           id=taskactivityid).activity.workCenter.name == 'Heat Treatment & Shot Peening':
        return render(request, 'WorkOrdersApp/infoTaskParts.html', context)

    elif get_object_or_404(TaskActivityModel,
                           id=taskactivityid).activity.workCenter.name == 'Welding':
        return render(request, 'WorkOrdersApp/infoTaskLaserCuttingParts.html', context)

    elif get_object_or_404(TaskActivityModel, id=taskactivityid).activity.workCenter.name == 'Brobo Rotary Saw':
        return render(request, 'WorkOrdersApp/infoTaskParts.html', context)

    elif get_object_or_404(TaskActivityModel, id=taskactivityid).activity.workCenter.name == 'Shakeout':
        return render(request, 'WorkOrdersApp/infoTaskParts.html', context)

    elif get_object_or_404(TaskActivityModel, id=taskactivityid).activity.workCenter.name == 'Sheet Metal Folding':
        return render(request, 'WorkOrdersApp/infoTaskParts.html', context)

    elif get_object_or_404(TaskActivityModel, id=taskactivityid).activity.workCenter.name == 'Ordering':
        taskPartsOrdered = TaskPartsModel.objects.filter(task=taskid)
        return render(request, 'WorkOrdersApp/infoTaskOrderingParts.html', {'orderedparts': taskPartsOrdered,
                                                                            'taskid': taskid,
                                                                            'taskactivity': taskactivity})
    elif get_object_or_404(TaskActivityModel, id=taskactivityid).activity.workCenter.name == 'Assembly':
        return render(request, 'WorkOrdersApp/infoTaskAssemblyParts.html', context)

    elif get_object_or_404(TaskActivityModel, id=taskactivityid).activity.workCenter.name == 'Hose Cutting':
        return render(request, 'WorkOrdersApp/infoTaskHoseCuttingParts.html', context,)


def info_task_part_include(request, taskid, taskactivityid, increment):
    taskactivity = get_object_or_404(TaskActivityModel, id=taskactivityid)
    task = get_object_or_404(TaskModel, id=taskid)
    taskparts = TaskPartsModel.objects.filter(task=task, activity=taskactivity)
    parts = PartModel.objects.all()

    if request.method == 'POST':
        form = TaskActivityPartsForm(request.POST)
        if form.is_valid():
            form.save()
            return info_task_parts(request, taskid, taskactivityid)

    initial = {'activity': taskactivity,
               'task': task,
               'increment': increment,
               'quantityCompleted': 0,
               'order': 100_000,
               'user': request.user
               }
    form = TaskActivityPartsForm(initial=initial)
    context = {"parts": parts,
               "partform": form,
               "taskparts": taskparts,
               "task": task,
               "taskactivity": taskactivity}

    return render(request, 'WorkOrdersApp/addTaskActivityParts.html', context)


class TaskPartRequiredUpdate(UpdateView):

WorkOrdersApp/templates/WorkOrdersApp/addTask.html
{% extends "includes/base.html" %}

{% load crispy_forms_tags %}

{% block body %}

<div class="container-fluid">
    <div class="row">
        <div class="col-sm">
            <form method="POST">
                <br>
                {% csrf_token %}
                {% crispy taskform %}
            </form>
        </div>
    </div>
    <div>
        <form class="form-inline">
            <input class="form-control" type="text" id="searchBar" onkeyup="search()" placeholder="Search" aria-label="Search">
        </form>
        <table class="table table-hover" id="selection">
            <thead>
            <tr>
                <th>Group Name</th>
            </tr>
            </thead>
            <tbody>
            {% for group in groups %}
            <tr data-gid="{{ group.id }}">
                <td>{{ group.groupName }}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

WorkOrdersApp/templates/WorkOrdersApp/addTaskActivity.html
{% extends "includes/base.html" %}

{% load crispy_forms_tags %}

{% block body%}


<div class="row">
    <div class="col-sm">
        <a href="{% url 'tasks' %}" class="badge badge-light">Tasks</a>>
        <a href="{% url 'infotaskactivities' task.id %}" class="badge badge-light">{{ task.taskName }}</a>

        <p class="font-weight-bold">Include Activity</p>
        <br>
        <br>
        <form class="form-inline">
            <input class="form-control" type="text" id="searchBar" onkeyup="search()" placeholder="Search" aria-label="Search">
        </form>
        <br>
        <br>
        <table class="table table-hover" id="selection">
            <thead>
            <tr>
                <th>Activity</th>
                <th>Description</th>
            </tr>
            </thead>
            <tbody>
            {% for activity in activities %}
            <tr data-aid="{{ activity.id }}">
                <td>{{ activity.activityName }}</td>
                <td>{{ activity.description }}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="col-sm">
        <div class="container">
            <form method="POST">
                {% csrf_token %}
                {% crispy activitiesform %}
            </form>
        </div>
        <table class="table table-hover">
            <thead>
            <tr>
                <th>Activity</th>
                <th>Description</th>
            </tr>
            </thead>
            <tbody>
            {% for activity in taskactivities %}
            <tr>
                <td>{{ activity.activity.activityName }}</td>
                <td>{{ activity.activity.description }}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

WorkOrdersApp/templates/WorkOrdersApp/infoTaskAssemblyParts.html
{% extends "includes/base.html" %}
{% load static %}
{% block body %}

<br>
<a href="{% url 'tasks' %}" class="badge badge-light">Tasks</a>>
<a href="{% url 'infotaskactivities' taskid %}" class="badge badge-light">Activities</a>
<br>
<p class="font-weight-bold">{{ taskactivity.activity }}</p>
<ul class="nav nav-tabs">
    <li><a class="nav-link active" data-toggle="tab" href="#instruction">Instruction</a></li>
    <li><a class="nav-link" data-toggle="tab" href="#parts">Parts</a></li>
</ul>
<div class="tab-content">
    <div id="instruction" class="tab-pane active">
        {% for instruction in instructions %}
        <iframe src='{{ instruction.pdf.url }}#toolbar=0' width="80%" height="400px"></iframe>
        {% endfor %}

    </div>
    <div id="parts" class="tab-pane">


        <table class="table table-hover" id="selection">
            <thead>
            <tr>
                <th colspan="6" style="text-align: center"> Parts Required</th>
            </tr>
            <tr>
                <th>Image</th>
                <th>Part Number</th>
                <th>Description</th>
                <th>Required</th>
                <th>Completed</th>
                <th>Complete</th>

            </tr>
            </thead>

            <tbody>

            {% for part in requiredparts %}

            <tr {% if part.quantityRequired == part.quantityCompleted %} class="table-success" {% endif %}
                {% if part.low %} class="table-danger" {% endif %}>
                <td><img src="{{ part.thumbnail.image.url }}" style="height: 100px;"/></td>
                <td>{{ part.part.partNumber }}</td>
                <td>{{ part.part.description }}</td>
                <td>
                    <form class="silent_form" method="POST" action="{% url 'edittaskpart-required' part.pk %}">

                        {% csrf_token %}
                        <input type="number" value="{{ part.quantityRequired }}" name="quantityRequired"
                               id="id_quantityRequired" class="input-group col-md-3">
                        <br/>

                        <input type="submit" class="btn btn-warning" value="Amend">
                    </form>
                </td>
                <td>
                    <form class="silent_form" method="POST" action="{% url 'edittaskpart-completed' part.pk %}">
                        {% csrf_token %}
                        <input type="number" value="{{ part.quantityCompleted }}" name="quantityCompleted"
                               id="id_quantityCompleted" class="input-group col-md-3">
                        <br/>

                        <input type="submit" class="btn btn-primary" value="Complete" onclick="
                                    $(this).prev().prev().val({{ part.quantityRequired }})">
                    </form>
                </td>
                <form action="{% url 'deletetaskpart' part.pk %}" method="post"
                      style="display: inline;">
                    <td>
                        {% csrf_token %}
                        <input type="submit" class="btn btn-danger" value="Delete"
                               onclick="return confirm('Are you sure you want to delete {{ part.part.partNumber }} from {{ taskactivity.activity }}?');">
                    </td>
                </form>
            </tr>

            {% endfor %}

            </tbody>

        </table>
        <div>
            <a href="{% url 'includerequiredpart' taskid taskactivity.id %}" class="btn btn-secondary btn-sm btn-pad"
               role="button">Include Part</a>
        </div>
        <table class="table table-hover" id="selection">
            <thead>
            <tr>
                <th colspan="6" style="text-align: center"> Parts Produced</th>
            </tr>
            <tr>
                <th>Image</th>
                <th>Part Number</th>
                <th>Description</th>
                <th>Required</th>
                <th>Completed</th>
                <th>Complete</th>

            </tr>
            </thead>

            <tbody>

            {% for part in producedparts %}

            <tr class="{% if part.quantityRequired == part.quantityCompleted %} table-success{% endif %}">
                <td><img src="{{ part.thumbnail.image.url }}" style="height: 100px;"/></td>
                <td>{{ part.part.partNumber }}</td>
                <td>{{ part.part.description }}</td>
                <td>
                    <form class="silent_form" method="POST" action="{% url 'edittaskpart-required' part.pk %}">

                        {% csrf_token %}
                        <input type="number" value="{{ part.quantityRequired }}" name="quantityRequired"
                               id="id_quantityRequired" class="input-group col-md-3">
                        <br/>

                        <input type="submit" class="btn btn-warning" value="Amend">
                    </form>
                </td>
                <td>
                    <form class="silent_form" method="POST" action="{% url 'edittaskpart-completed' part.pk %}">
                        {% csrf_token %}
                        <input type="number" value="{{ part.quantityCompleted }}" name="quantityCompleted"
                               id="id_quantityCompleted" class="input-group col-md-3">
                        <br/>

                        <input type="submit" class="btn btn-primary" value="Complete" onclick="
                                    $(this).prev().prev().val({{ part.quantityRequired }})">
                    </form>
                </td>
                <form action="{% url 'deletetaskpart' part.pk %}" method="post"
                      style="display: inline;">
                    <td>
                        {% csrf_token %}
                        <input type="submit" class="btn btn-danger" value="Delete"
                               onclick="return confirm('Are you sure you want to delete {{ part.part.partNumber }} from {{ taskactivity.activity }}?');">
                    </td>
                </form>
            </tr>

            {% endfor %}

            </tbody>

        </table>

        {% endblock %}
    </div>
</div>

WorkOrdersApp/templates/WorkOrdersApp/infoTaskParts.html
{% extends "includes/base.html" %}
{% load static %}
{% block body %}

<br>
<form class="form-inline my-2 my-lg-0">
    <input class="form-control mr-sm-2" type="text" id="searchBar" onkeyup="search()" placeholder="Search" aria-label="Search">
</form>

<br>
<form method="POST">

    <table class="table table-hover" id="selection">
        <thead>
        <tr>
            <th>Parts</th>

        </tr>
        </thead>

        <tbody>

        {% for part in requiredparts %}

        <tr>
            <td><img src="{{ part.thumbnail.image.url }}" style="height: 100px;"/></td>
            <td>{{ part.part.partNumber }}</td>
            <td>{{ part.quantityRequired }}</td>
            <td>
                <input type="number" value="{{ part.quantityCompleted }}" name="{{ part.pk }}">
            </td>
            <td><button type="button" data-partid="{{ part.pk }}" data-value="{{ part.quantityRequired }}" class="setbutton">complete</button></td>
        </tr>

        {% endfor %}

        </tbody>

    </table>
    <input id="submit-id-save" type="submit">
    {% csrf_token %}
</form>
{% endblock %}

WorkOrdersApp/templates/WorkOrdersApp/infoTaskPickingParts.html
{% extends "includes/base.html" %}
{% load static %}
{% block body %}

<a href="{% url 'tasks' %}" class="badge badge-light">Tasks</a>>
<a href="{% url 'infotaskactivities' taskid %}" class="badge badge-light">Activities</a>
<br>
<p class="font-weight-bold">{{ taskactivity.activity }}, {{ taskactivity.activity.description }} - Picking</p>

<table class="table table-hover" id="selection">
    <thead>
    <tr>
        <th colspan="6" style="text-align: center">Parts Required</th>
    </tr>
    <tr>
        <th>Image</th>
        <th>Part Number</th>
        <th>Description</th>
        <th>Location</th>
        <th>Extra Info</th>
        <th>Required</th>
        <th>Serial Number</th>
        <th>Complete</th>

    </tr>
    </thead>

    <tbody>

    {% for part in requiredparts %}

    <tr {% if part.quantityRequired == part.quantityCompleted %} class="table-success" {% endif %}
        {% if part.low %} class="table-danger" {% endif %}>
        <td><img src="{{ part.thumbnail.image.url }}" style="height: 100px;"/></td>
        <td>{{ part.part.partNumber }}</td>
        <td>{{ part.part.description }}</td>
        <td>{{ part.part.location }}</td>
        <td>{{ part.extra }}</td>
        <td>
            <form class="silent_form" method="POST" action="{% url 'edittaskpart-required' part.pk %}">

                {% csrf_token %}
                <input type="number" value="{{ part.quantityRequired }}" name="quantityRequired"
                       id="id_quantityRequired" class="input-group col-md-10">
                <br/>

                <input type="submit" class="btn btn-warning" value="Amend">
            </form>
        </td>
        <td>
            <form class="silent_form" method="POST" action="{% url 'edittaskpart-serial' part.pk %}">

                {% csrf_token %}
                <input type="text" value="{{ part.serial }}" name="serial"
                       id="id_serial" class="input-group col-md-6">
                <br/>

                <input type="submit" class="btn btn-warning" value="Update Serial Number">
            </form>
        </td>
        <td>
            <form class="silent_form" method="POST" action="{% url 'edittaskpart-completed' part.pk %}">
                {% csrf_token %}
                <input type="number" value="{{ part.quantityCompleted }}" name="quantityCompleted"
                       id="id_quantityCompleted" class="input-group col-md-8">
                <br/>

                <input type="submit" class="btn btn-primary" value="Complete" onclick="
                                    $(this).prev().prev().val({{ part.quantityRequired }})">
            </form>
        </td>
        <form action="{% url 'deletetaskpart' part.pk %}" method="post"
              style="display: inline;">
            <td>
                {% csrf_token %}
                <input type="submit" class="btn btn-danger" value="Delete"
                       onclick="return confirm('Are you sure you want to delete {{ part.part.partNumber }} from {{ taskactivity.activity }}?');">
            </td>
        </form>
    </tr>

    {% endfor %}

    </tbody>
    <thead>

    <tr>
        <th colspan="6" style="text-align: center"> Parts Produced</th>
    </tr>
    <tr>
        <th>Image</th>
        <th>Part Number</th>
        <th>Description</th>
        <th>Required</th>
        <th>Complete</th>

    </tr>
    </thead>

    <tbody>

    {% for part in producedparts %}

    <tr class="{% if part.quantityRequired == part.quantityCompleted %} table-success{% endif %}">
        <td><img src="{{ part.thumbnail.image.url }}" style="height: 100px;"/></td>
        <td>{{ part.part.partNumber }}</td>
        <td>{{ part.part.description }}</td>

        <td>
            <form class="silent_form" method="POST" action="{% url 'edittaskpart-required' part.pk %}">

                {% csrf_token %}
                <input type="number" value="{{ part.quantityRequired }}" name="quantityRequired"
                       id="id_quantityRequired" class="input-group col-md-4">
                <br/>

                <input type="submit" class="btn btn-warning" value="Amend">
            </form>
        </td>
        <td>
            <form class="silent_form" method="POST" action="{% url 'edittaskpart-completed' part.pk %}">
                {% csrf_token %}
                <input type="number" value="{{ part.quantityCompleted }}" name="quantityCompleted"
                       id="id_quantityCompleted" class="input-group col-md-4">
                <br/>

                <input type="submit" class="btn btn-primary" value="Complete" onclick="
                                    $(this).prev().prev().val({{ part.quantityRequired }})">
            </form>
        </td>
        <form action="{% url 'deletetaskpart' part.pk %}" method="post"
              style="display: inline;">
            <td>
                {% csrf_token %}
                <input type="submit" class="btn btn-danger" value="Delete"
                       onclick="return confirm('Are you sure you want to delete {{ part.part.partNumber }} from {{ taskactivity.activity }}?');">
            </td>
        </form>
    </tr>

    {% endfor %}

    </tbody>

</table>
<div>
    <a href="{% url 'includerequiredpart' taskid taskactivity.id %}" class="btn btn-secondary btn-sm btn-pad"
       role="button">Include Required Part</a>
</div>
<br>


{% endblock %}