MainApp/urls.py
from django.urls import path
from .views import *
from InventoryOutput import export_stocktake_csv

urlpatterns = [
    path("register/", register, name="register"),
    path("logout/", logout_request, name="logout"),
    path("login/", login_request, name="login"),
    path("composertest/", composer_test, name="composertest"),
    path("export/", export_stocktake_csv, name='export_stocktake_csv'),
]

PartsApp/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', list_parts, name='inventory'),  # URL path for inventory_list view
    path('history', PartHistoryListView.as_view(), name='parts_history'),  # URL path for inventory_list view
    path('addpart/', add_part, name='addpart'),
    path('parts/<int:part_id>/', info_part, name='info_part'),
    path('parts/<int:part_id>/delete-inventory-images/', delete_inventory_images, name='delete_inventory_images'),
    path('parts/<int:part_id>/lowstockgroup', low_stock_group, name='lowstockgroup'),
    path('parts/<int:part_id>/print', print_inventory_label, name='printlabel'),
    path('parts/editsupplierpartnumber/<int:pk>', SupplierPartNumberUpdate.as_view(), name='editsupplierpartnumber'),
    path('parts/<int:part_id>/addsupplier', add_supplier_to_part, name='addpartsupplier'),
    path('addsupplier', add_supplier, name='addsupplier'),
    path("suppliers/", list_supplier, name="suppliers"),
    path('suppliers/<int:id>/', info_supplier, name='info_supplier'),
]

TrojanProject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import PartsApp
from PartsApp.views import qr_scan

urlpatterns = [
    path('', qr_scan),
    path('admin/', admin.site.urls),
    path('main/',include('MainApp.urls')),
    path('inventory/',include('PartsApp.urls')),
    path('activities/', include('ActivitiesApp.urls')),
    path('workorders/', include('WorkOrdersApp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PartsApp/models.py
# Create your models here.
from django.db import models, transaction
from django.contrib.auth.models import User
from simple_history.models import HistoricalRecords
from django.utils.html import mark_safe
from django.dispatch import receiver
from django.db.models.signals import post_save, post_delete
from django.core.files.storage import default_storage


# Inventory Model with fields
# from ActivitiesApp.models import GroupModel, GroupActivityModel, ActivityPartModel
# from WorkOrdersApp.models import TaskModel, TaskActivityModel, TaskPartsModel


class PartModel(models.Model):
    partNumber = models.CharField(max_length=50, blank=False, unique=True)
    description = models.CharField(max_length=200)
    location = models.CharField(max_length=40)
    stockOnHand = models.IntegerField(blank=True)
    minimumStock = models.IntegerField(blank=True)
    reorderQtys = models.IntegerField(blank=True)
    boxSize = models.IntegerField(blank=True)
    leadtime = models.CharField(max_length=50)
    weight = models.IntegerField(blank=True)
    obsolete = models.BooleanField(default=False)
    group = models.ForeignKey("ActivitiesApp.GroupModel", on_delete=models.PROTECT, blank=True, null=True)
    history = HistoricalRecords()

    def getPreferredSupplier(self):
        supplierList = PartSupplierModel.objects.filter(part=self.id, preferred=True)
        if supplierList.count() == 0:
            return None
        return supplierList.first().supplier

    def __str__(self):
        return self.partNumber

@receiver(post_save, sender=PartModel)
def lowstocktaskcreate(sender,instance,created,**kwargs):
    from ActivitiesApp.models import GroupModel, GroupActivityModel, ActivityPartModel
    from WorkOrdersApp.models import TaskModel, TaskActivityModel, TaskPartsModel

    if instance.group is not None:
        tasks = TaskModel.objects.all()
        print(User.objects.all())
        activeList = [task for task in tasks if not task.userGroupCompleted(User.objects.all())]
        if not activeList.objects.filter(group=instance.group):
            group = instance.group
            task = TaskModel(taskName='Trojan',
                            fleetNumber='Restock',
                            group=group)
            # task.save()
            groupactivitylist = GroupActivityModel.objects.filter(group=group).order_by('order')

            for groupactivity in groupactivitylist:
                tempactivity = TaskActivityModel(task=task,
                                                    activity=groupactivity.activity)
                # tempactivity.save()
                required_list = ActivityPartModel.objects.filter(activity=groupactivity.activity).order_by('id')
                for required in required_list:
                    temp = TaskPartsModel(activity=tempactivity,
                                            part=required.part,
                                            task=task,
                                            increment=required.increment,
                                            quantityRequired=required.quantity,
                                            order=required.order,
                                            extra=required.location,
                                            quantityCompleted=0,
                                         )
                    # temp.save()
    else:
        pass


class SupplierModel(models.Model):
    supplierName = models.CharField(max_length=50)

    def __str__(self):
        return self.supplierName


# lookup for many to many relationship between parts and Suppliers
class PartSupplierModel(models.Model):
    supplierPartNumber = models.CharField(max_length=50, null=True)
    supplier = models.ForeignKey(SupplierModel, on_delete=models.CASCADE)
    part = models.ForeignKey(PartModel, on_delete=models.CASCADE)
    preferred = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        if not self.preferred:
            if PartSupplierModel.objects.filter(part=self.part).count() == 0:
                self.preferred = True
            return super(PartSupplierModel, self).save(*args, **kwargs)
        with transaction.atomic():
            PartSupplierModel.objects.filter(part=self.part, preferred=True) \
                .update(preferred=False)
            return super(PartSupplierModel, self).save(*args, **kwargs)

    def __str__(self):
        return str(self.supplier) + " - " + str(self.supplierPartNumber)


class PartCommentModel(models.Model):
    timestamp = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.PROTECT)
    part = models.ForeignKey(PartModel, on_delete=models.PROTECT)
    comment = models.TextField()

    def __str__(self):
        return str(self.timestamp.strftime("%d/%m/%Y")) + " - " + str(self.author) + " - " + str(self.comment)


class PartImageModel(models.Model):
    part = models.ForeignKey(PartModel, on_delete=models.PROTECT)
    image = models.ImageField(upload_to='images/')

    @classmethod
    def delete_associated_files(sender, instance, **kwargs):
        """Remove all files of an image after deletion."""
        path = instance.image.name
        if path:
            default_storage.delete(path)

    def image_tag(self):
        return mark_safe('<img src="/media/images/%s" width="150" height="150" />' % (self.image))

    image_tag.short_description = 'Image'

post_delete.connect(PartImageModel.delete_associated_files, sender=PartImageModel)

PartsApp/views.py
# Create your views here.
from functools import reduce

from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.urls import reverse
from django.db.models import Q
from django.utils import timezone
from django.views.generic import ListView, UpdateView
from BrotherQL270NW.imageTest import print_label
from ActivitiesApp.models import ActivityPartModel, GroupModel
from WorkOrdersApp.models import TaskModel
from WorkOrdersApp.forms import TaskForm, TaskPartsModel
from .forms import *


# Create your views here.
@login_required
def qr_scan(request):
    searchQuery = request.GET.get('q', None)
    fields = request.GET.keys()
    # print(list(fields))
    context = {
        'header': 'Scanner',
        'infoText': 'Please scan first'
    }
    if searchQuery is not None and searchQuery != '':

        parts = None
        query = Q()
        # if 'partnumbercheck' in fields:
        query.add(Q(partNumber__contains=searchQuery), Q.OR)

        # if 'descriptioncheck' in fields:
        #     query.add(Q(description__contains=searchQuery), Q.OR)
        #
        # if 'locationcheck' in fields:
        #     query.add(Q(location__contains=searchQuery), Q.OR)

        if len(query) == 0:
            context['infoText'] = f'Nothing found, please select a checkbox'
            return render(request, 'PartsApp/partsQrScan.html', context)

        parts = PartModel.objects.filter(query)

        if parts == None or parts.count() == 0:
            context['infoText'] = f'Nothing found for partNumber "{searchQuery}"'
        elif parts.count() == 1:

            part = parts.first()

            # info_part(request, part.id)
            return redirect('info_part', part.id)

        else:
            # print(f'{parts=}')

            for part in parts:
                part.low = part.stockOnHand < part.minimumStock
            for part in parts:
                part.supplier = part.getPreferredSupplier()

            context = {
                'parts': parts,
                'header': 'Inventory'
            }

            return render(request, 'PartsApp/partsQrScan.html', context)

    return render(request, 'PartsApp/partsQrScan.html', context)


@login_required
def list_parts(request):
    parts = PartModel.objects.all()
    for part in parts:
        part.low = part.stockOnHand < part.minimumStock
    for part in parts:
        part.supplier = part.getPreferredSupplier()

    context = {
        'parts': parts,
        'header': 'Inventory'
    }

    return render(request, 'PartsApp/listParts.html', context)


class PartHistoryListView(ListView):
    model = PartModel.history.model

    paginate_by = 100  # if pagination is desired

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context

    # def get_queryset(self):
    #     model = PartModel.objects.history.all()
    #     for part in model:
    #         part.change = part.stockOnHand - part.prev_record.stockOnHand
    #         print(part.change)
    #     return model


@login_required
def list_supplier(request):
    context = {
        'header': 'Supplier List',
        'suppliers': SupplierModel.objects.all(),
    }
    return render(request, 'PartsApp/listSuppliers.html', context)


def print_inventory_label(request, part_id):
    part = PartModel.objects.get(id=part_id)
    print_label(part.partNumber, part.description)
    return redirect("info_part", part_id)


@login_required
def info_part(request, part_id):
    # print("working")
    part = PartModel.objects.all().filter(pk=part_id).first()

    if request.method == "POST":
        # from pprint import pprint
        # pprint(request.POST)
        # print("---")

        imageform = ImageForm(request.POST, request.FILES,
                              initial={'part': part})
        form1 = PartForm(request.POST, instance=part)
        form2 = PartCommentForm(request.POST, initial={
                                'author': request.user, 'part': part})
        if form1.is_valid():
            part = form1.save()
            # update_change_reason(part, 'Manual')
        if form2.is_valid():
            form2.save()
        if imageform.is_valid():
            imageform.save()

    imageform = ImageForm(initial={'part': part})
    image = PartImageModel.objects.filter(part=part)
    form1 = PartForm(instance=part)
    # taskform = LowStockTaskForm(instance=part)
    form2 = PartCommentForm(initial={'author': request.user, 'part': part})
    movements = part.history.all().reverse()
    previouslevel = 0
    # activities = GroupActivityModel.objects.filter(activity__activitypartmodel__part=part)
    #
    # for activity in activities:
    #     activity.qty = ActivityPartModel.objects.filter(activity=activity.activity, part=part).aggregate(
    #         Sum("quantity"))

    activities = ActivityPartModel.objects.filter(part=part)

    for movement in movements:
        movement.change = movement.stockOnHand - previouslevel
        previouslevel = movement.stockOnHand

    context = {'partform': form1,
               'part': part,
               'images': image,
               'imageform': imageform,
               'partsuppliers': PartSupplierModel.objects.filter(
                   part=part.id),
               'commentForm': form2,
               'part_id': part.id,
               'movements': reversed(movements),
               'activities': activities,
               'partcomments': PartCommentModel.objects.all().filter(part=part.id),
               }

    return render(request, 'PartsApp/infoPart.html', context)


@login_required
def low_stock_group(request, part_id):
    groups = GroupModel.objects.all()
    part = PartModel.objects.filter(pk=part_id)
    if request.method == "POST":
        form = LowStockGroupForm(request.POST, initial={
                                 'partNumber': part_id}, instance=part.first())
        if form.is_valid():
            form.save()

        return redirect('info_part', part_id)

    else:
        form = LowStockGroupForm(instance=part.first())
        context = {'LowStockGroupForm': form,
                   'part': part,
                   'groups': groups,
                   }
    return render(request, 'PartsApp/lowstockgroup.html', context)


class SupplierPartNumberUpdate(UpdateView):
    http_method_names = ['post']
    model = PartSupplierModel
    fields = ['supplierPartNumber']

    def get_success_url(self):
        return reverse('info_part', args=[str(self.object.part.pk)])


@login_required
def delete_inventory_images(request, part_id):
    images_to_delete = request.POST.getlist('to_delete[]')
    print(part_id)
    print(images_to_delete)
    print(PartImageModel.objects.get(part=part_id, image__in=images_to_delete))
    instance = PartImageModel.objects.get(
        image__in=images_to_delete).delete()
    return redirect(request.META.get('HTTP_REFERER', '/'))


@login_required
def info_supplier(request, id):
    supplierparts = PartSupplierModel.objects.filter(supplier=id)
    if request.method == "POST":
        if 'supplierform-supplierName' in request.POST:
            supplierform = SupplierForm(request.POST, instance=SupplierModel.objects.filter(pk=id),
                                        prefix='supplierform')
            if supplierform.is_valid():
                supplierform.save()
                return redirect('suppliers')
        elif 'taskForm-taskName' in request.POST:
            taskform = TaskForm(request.POST, prefix='taskForm')
            if taskform.is_valid():
                ordertask = taskform.save()
                for part in supplierparts:
                    quantity = int(request.POST.get(f'{part.part.pk}'))
                    if quantity > 0:
                        temp = TaskPartsModel(task=ordertask,
                                              part=part.part,
                                              increment=True,
                                              quantityRequired=quantity,
                                              quantityCompleted=0,
                                              )
                        temp.save()

            return redirect('suppliers')

    else:
        for part in supplierparts:
            part.low = part.part.stockOnHand < part.part.minimumStock
            part.ordered = 0
        supplierform = SupplierForm(instance=SupplierModel.objects.all().filter(
            pk=id).first(), prefix='supplierform')
        taskform = TaskForm(prefix='taskForm')
        return render(request, 'PartsApp/infoSupplier.html', {'supplierform': supplierform,
                                                              'supplierparts': supplierparts,
                                                              'taskform': taskform})


@login_required
def add_supplier(request):
    if request.method == "POST":
        form = SupplierForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('suppliers')

    else:
        form = SupplierForm()
        return render(request, 'PartsApp/addSupplier.html', {'supplierForm': form})


@login_required
def add_part(request):
    if request.method == "POST":
        form = PartForm(request.POST)

        if form.is_valid():
            form.save()
            partnumber = form.cleaned_data['partNumber']
            part_id = PartModel.objects.get(partNumber__exact=partnumber)
            return info_part(request, part_id.id)

    else:
        form = PartForm()
        return render(request, 'PartsApp/addPart.html', {'PartForm': form})


@login_required
def add_supplier_to_part(request, part_id):
    suppliers = SupplierModel.objects.all()
    part = PartModel.objects.filter(pk=part_id)
    partsuppliers = PartSupplierModel.objects.filter(part=part_id)
    if request.method == "POST":
        form = PartSupplierForm(request.POST)

PartsApp/templates/PartsApp/addPart.html
{% extends "includes/base.html" %}

{% load crispy_forms_tags %}

{% block body%}

<div class="container-fluid">
    <br>
    {% csrf_token %}
    {% crispy PartForm %}
</div>

{% endblock %}

PartsApp/templates/PartsApp/addPartSupplier.html
{% extends "includes/base.html" %}

{% load crispy_forms_tags %}

{% block body%}

<br>
    <div class="row">
        <div class="col-sm">
            <br>
            <br>
            <br>
            <br>
            <br>
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="text" id="searchBar" onkeyup="search()" placeholder="Search" aria-label="Search">
            </form>
            <br>
            <table class="table table-hover" id="selection">
                <thead>
                <tr>
                    <th>All Suppliers</th>
                </tr>
                </thead>
                <tbody>
                {% for supplier in suppliers %}
                <tr data-sid="{{ supplier.id }}">
                    <td>{{ supplier.supplierName }}</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="col-sm">
            <div class="container">
                <form method="POST">
                    {% csrf_token %}
                    {% crispy partsupplierform %}
                </form>
            </div>
            <br>
            <table class="table table-hover">
                <thead>
                <tr>
                    <th>Part Suppliers</th>
                </tr>
                </thead>
                <tbody>
                {% for supplier in partsuppliers %}
                <tr data-href="{% url 'info_supplier' supplier.supplier.id %}">
                    <td>{{ supplier.supplierPartNumber }}</td>
                    <td>{{ supplier.supplier.supplierName }}</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>


{% endblock %}

PartsApp/templates/PartsApp/addSupplier.html
{% extends "includes/base.html" %}

{% load crispy_forms_tags %}

{% block body%}

<div class="container-fluid">
    <div class="row">
        <div class="col-sm">
            <form method="POST">
                <br>
                {% csrf_token %}
                {% crispy supplierForm %}
            </form>
        </div>
    </div>
</div>

{% endblock %}

PartsApp/templates/PartsApp/historicalpartmodel_list.html
{% extends "includes/base.html" %}
{% load static %}
{% block body %}
{##}
{#<h1>Articles</h1>#}
{#<ul>#}
{#    {% for partHistory in object_list %}#}
{#        <li>{{ partHistory.partNumber }} - {{ partHistory.stockOnHand }}</li>#}
{#    {% empty %}#}
{#        <li>No articles yet.</li>#}
{#    {% endfor %}#}
{#</ul>#}


<table class="table table-hover" id="selection">
    <thead>
    <tr>
        <th>Part Number</th>
        <th>Description</th>
        <th>User</th>
        <th>Time</th>
        <th>Update</th>
        <th>S.O.H</th>
    </tr>
    </thead>

    <tbody>

    {% for part in object_list %}

        <tr data-href="{% url 'info_part' part.id %}"
                {% if part.obsolete %} class="table-dark" {% endif %}
                {% if part.low %} class="table-danger" {% endif %}>
            <td>{{ part.partNumber }}</td>
            <td>{{ part.description }}</td>
            <td>{{ part.history_user }}</td>
            <td>{{ part.history_date }}</td>
            <td>{{ part.history_change_reason }}</td>
            <td>{{ part.stockOnHand }}</td>
        </tr>

    {% endfor %}

    </tbody>

</table>

{% endblock %}

PartsApp/templates/PartsApp/infoPart.html
{% extends "includes/base.html" %}

{% load crispy_forms_tags %}

{% block body %}
<a href="{% url 'inventory' %}" class="badge badge-light">Inventory</a>
<a href="{% url 'printlabel' part_id %}" ><button>Print Label</button></a>
<div class="container-fluid">
    <div class="row">
        <div class="col">
            <form method="POST">
                <br>
                {% csrf_token %}
                {% crispy partform %}
            </form>
            <br>
            <a href="{% url 'lowstockgroup' part_id %}" ><button class="btn btn-warning">Group Selection</button></a>
            <br>
            <table class="table table-hover">
                <tbody>
                {% for comment in partcomments %}
                <tr>
                    <td>{{ comment }}</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
            <form method="POST">
                <br>
                {% csrf_token %}
                {% crispy commentForm %}
            </form>
            <br>
            <ul class="nav nav-pills nav-fill" id="myTab" role="tablist">
                <li class="nav-item">
                  <a class="nav-link active" id="view-tab" data-toggle="tab" href="#view" role="tab" aria-controls="view" aria-selected="true">View image</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" id="upload-tab" data-toggle="tab" href="#upload" role="tab" aria-controls="upload" aria-selected="false">Profile</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" id="contact-tab" data-toggle="tab" href="#delete" role="tab" aria-controls="delete" aria-selected="false">Delete</a>
                </li>
            </ul>
            <div class="tab-content" id="myTabContent" style="width:100%; height: 500px;" >
                <div class="tab-pane fade show active" id="view" role="tabpanel" aria-labelledby="view-tab">
                    <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
                        <div class="carousel-inner">
                            {% for image in images %}
                            <div class="carousel-item  {% if forloop.first %} {{ 'active' }} {% endif %}">
                            <img class="d-block w-100" src="{{ image.image.url }}"  width="700px" height="500px" style="object-fit: contain;"/>
                          </div>
                          {% endfor %}
                        </div>
                        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                          <span class="sr-only">Previous</span>
                        </a>
                        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                          <span class="carousel-control-next-icon" aria-hidden="true"></span>
                          <span class="sr-only">Next</span>
                        </a>
                      </div>
                </div>
                <div class="tab-pane fade" id="upload" role="tabpanel" aria-labelledby="upload-tab">
                    <div>
                        <br>
                        <form enctype="multipart/form-data" method="post">
                            {% csrf_token %}
                            {{ imageform.as_p }}
                            <button type="submit" class="btn btn-success">Upload</button>
                        </form>
                    </div>
                </div>
                <div class="tab-pane fade" id="delete" role="tabpanel" aria-labelledby="delete-tab">
                    <form class="form-group" action="{% url 'delete_inventory_images' part_id %}" method="POST">
                    {% csrf_token %}
                    <table class="table table-striped">
                        <thead>
                          <tr>
                            <th scope="col">#</th>  
                            <th scope="col">Image name</th>
                            <th scope="col">thumbnail</th>
                            <th scope="col">Delete?</th>
                          </tr>
                        </thead>
                        <tbody>
                        {% for image in images %}
                          <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td>{{ image.image.name }}</td>
                            <td> <img class="d-block w-100" src="{{ image.image.url }}"  width="50px" height="50px" style="object-fit: contain;"/> </td>
                            <td>
                                <div class="form-check">
                                    <input type="checkbox" value="{{ image.image.name }}" name="to_delete[]" class="form-check-input" >
                                </div>
                            </td>
                          </tr>
                        {% endfor %}
                        </tbody>
                      </table>
                      <button type="submit" name="delete-inventory-images" class="btn btn-danger" >Delete Images</button>
                    </form>
                </div>
            </div>
        </div>

        <div class="col">
            <div class='overflow-auto' style="height: 200px; overflow-y : scroll">
                <table class="table table-hover mb-0">
                    <thead>
                    <tr>
                        <th>Supplier</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for supplier in partsuppliers %}
                    <tr>
                        <td data-href="{% url 'info_supplier' supplier.supplier.id %}">{{ supplier }}</td>
                        <td>
                            <form method="POST" action="{% url 'editsupplierpartnumber' supplier.pk %}">

                                {% csrf_token %}
                                <input type="text" value="{{ supplier.supplierPartNumber }}" name="supplierPartNumber"
                                       id="id_supplierPartNumber" class="input-group col-md-5">
                                <input type="submit" class="btn btn-sm btn-warning" value="Update">
                            </form>
                        </td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>

            <a class="btn btn-secondary btn-sm btn-pad" href="{% url 'addpartsupplier' part_id=part_id %}"
               role="button">Add Supplier</a>

            <div class='overflow-auto' style="height: 300px; overflow-y : scroll">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th>Movements</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for movement in movements %}
                    <tr {% if movement.change < 0 %} class="table-danger" {% endif %}
                    {% if movement.change > 0 %} class="table-success" {% endif %}>
                    <td>{{ movement.history_date }}</td>
                    <td>{{ movement.history_user }}</td>
                    <td>{{ movement.change }}</td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>

            <div class='overflow-auto' style="height: 300px; overflow-y : scroll">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th>Used in</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for activity in activities %}
                    <tr {% if activity.increment == False %} class="table-danger" {% endif %}
                    {% if activity.increment == True %} class="table-success" {% endif %}
                    data-href="{% url 'activityinformation' activity.activity.id %}">
                        <td>{{ activity.activity.activityName }}</td>
                        <td>{{ activity.activity.description }}</td>
                        <td>{{ activity.quantity }}</td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>


{% endblock %}

PartsApp/templates/PartsApp/listParts.html
{% extends "includes/base.html" %}
{% load static %}
{% block body %}

    <br>

    <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="text" id="searchBar" onkeyup="search()" placeholder="Search"
               aria-label="Search">
    </form>

    <br>

    <div class="container-fluid">
        <a href="{% url 'addpart' %}" class="btn btn-secondary btn-sm btn-pad" role="button">New Part</a>
    </div>

    <br>

    <div class="container-fluid">
        <button class="low-stock-button btn btn-secondary btn-sm btn-pad" role="button">Low Stock</button>
    </div>

    <br>

    <table class="table table-hover" id="selection">
        <thead>
        <tr>
            <th>Part Number</th>
            <th>Description</th>
            <th>Location</th>
            <th>Supplier</th>
            <th>S.O.H</th>
        </tr>
        </thead>

        <tbody>

        {% for part in parts %}

            <tr data-href="{% url 'info_part' part.id %}"
                    {% if part.obsolete %} class="table-dark" {% endif %}
                    {% if part.low %} class="table-danger" {% endif %}>
                <td>{{ part.partNumber }}</td>
                <td>{{ part.description }}</td>
                <td>{{ part.location }}</td>
                <td>{{ part.supplier }}</td>
                <td>{{ part.stockOnHand }}</td>
            </tr>

        {% endfor %}

        </tbody>

    </table>

{% endblock %}