ActivitiesApp/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', activity_list, name='activities'),  # URL path for inventory_list view
    path('addactivity/', add_activity, name='addactivity'),
    path('activity/<str:id>/', activity_information, name='activityinformation'),
    path('activity/<str:id>/addrequired', add_required_part_to_activity, {'increment': False}, name='addrequired'),
    path('activity/<str:id>/addproduced', add_required_part_to_activity, {'increment': True}, name='addproduced'),
    path('activity/<str:id>/save-part-ordering', save_new_ordering_parts_of_activity, name='save-part-ordering'),

    path('activity/editpart/<int:pk>', ActivityPartUpdate.as_view(), name='editactivitypart'),

    path('activity/deletepart/<int:pk>', ActivityPartDelete.as_view(), name='deleteactivitypart'),
    # path('workcenters/', work_center, name='workcenters'),
    path('groups/', groups, name='groups'),
    path('groups/addgroup/', add_group, name='addgroup'),
    path('groups/<int:id>/', group_information, name='groupinformation'),
    path('groups/<int:id>/save-activity-ordering', save_new_ordering_activities_of_group, name='save-activity-ordering'),
    path('groups/deletegroupactivity/<int:pk>', GroupActivityDelete.as_view(), name='deletegroupactivity'),

    path('groups/<int:id>/addrequired', add_required_activity_to_group, name='addrequiredactivity'),

]

MainApp/urls.py
from django.urls import path
from .views import *
from InventoryOutput import export_stocktake_csv

urlpatterns = [
    path("register/", register, name="register"),
    path("logout/", logout_request, name="logout"),
    path("login/", login_request, name="login"),
    path("composertest/", composer_test, name="composertest"),
    path("export/", export_stocktake_csv, name='export_stocktake_csv'),
]

TrojanProject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import PartsApp
from PartsApp.views import qr_scan

urlpatterns = [
    path('', qr_scan),
    path('admin/', admin.site.urls),
    path('main/',include('MainApp.urls')),
    path('inventory/',include('PartsApp.urls')),
    path('activities/', include('ActivitiesApp.urls')),
    path('workorders/', include('WorkOrdersApp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ActivitiesApp/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
# from django.contrib.postgres.fields import ArrayField
from PartsApp.models import PartModel
from django.contrib.auth.models import User, Group
from simple_history.models import HistoricalRecords


# class WorkCenterTypes(models.Model):
#     wcType = models.CharField(max_length=2)
#     description = models.CharField(max_length=50)
#
#     def __str__(self):
#         return f'{self.wcType} - {self.description}'
#
#         # PICKING = 'PK', _('Picking')
#         # LAZERCUTTING = 'LC', _('Lazer Cutting')
#         # POWDERCOATING = 'PC', _('Powder Coating')
#         # ZINCCOATING = 'ZN', _('Zinc Coating')
#         # HEATTREAT = 'HT', _('Heat Treatment & Shot Peening')
#         # ROTARYSAW = 'RS', _('Brobo Rotary Saw')
#         # SHAKEOUT = 'SK', _('Shakeout')
#         # FOLDING = 'FD', _('Sheet Metal Folding')


class ActivityModel(models.Model):
    activityName = models.CharField(max_length=100)
    description = models.CharField(max_length=200)
    workCenter = models.ForeignKey(Group, on_delete=models.PROTECT)
    history = HistoricalRecords()

    def __str__(self):
        return str(self.activityName)

    def getStatus(self):
        parts = ActivityPartModel.objects.filter(activity=self,
                                                 increment=False,
                                                 part__stockOnHand__gt=0)

        if parts.count() == 0:
            return "Waiting"

        return "Active"


class ActivityPartModel(models.Model):
    activity = models.ForeignKey(ActivityModel, on_delete=models.CASCADE)
    part = models.ForeignKey("PartsApp.PartModel", on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    increment = models.BooleanField(default=False)  # TRUE/FALSE used to represent parts ActivityPartModel/produced
    order = models.IntegerField(blank=False, default=100_000)
    location = models.TextField(max_length=50, null=True)
    history = HistoricalRecords()

    def updateQuantity(self, newval):
        self.quantity = newval
        self.save()

    def __str__(self):
        return str(self.activity) + " - " + str(self.part)

class GroupModel(models.Model):
    groupName = models.CharField(max_length=50)

    def __str__(self):
        return self.groupName


class GroupActivityModel(models.Model):
    group = models.ForeignKey(GroupModel, on_delete=models.PROTECT)
    activity = models.ForeignKey(ActivityModel, on_delete=models.PROTECT)
    order = models.IntegerField(blank=False, default=100_000)

    def __str__(self):
        return str(self.group) + ' - ' + str(self.activity)

# class GroupTriggerModel(models.Model):
#     completedGroup = models.ForeignKey(GroupModel, related_name='completed_group', on_delete=models.CASCADE)
#     triggerGroup = models.ForeignKey(GroupModel, related_name='trigger_group', on_delete=models.CASCADE)

class instruction(models.Model):
    activity = models.ForeignKey(ActivityModel, on_delete=models.CASCADE)
    pdf = models.FileField(upload_to='pdf')

ActivitiesApp/views.py
from django.db import transaction
from django.urls import reverse_lazy, reverse
from django.views.decorators.http import require_POST
from django.views.generic import UpdateView, DeleteView
from simple_history.utils import update_change_reason

from PartsApp.models import PartImageModel, PartModel
from .models import *
from django.shortcuts import render, redirect, get_object_or_404
from .forms import *
from django.contrib import messages
from django.utils import timezone
from django.contrib.auth.decorators import login_required


# Create your views here.
@login_required
def activity_list(request):
    return render(request, 'ActivitiesApp/listActivities.html', {'header': 'ActivityModel',
                                                                 'activities': ActivityModel.objects.all()})


@login_required
def add_activity(request):
    if request.method == "POST":
        form = activity_form(request.POST)

        if form.is_valid():
            form.save()
            return redirect('activities')

    else:
        form = activity_form()

        return render(request, 'ActivitiesApp/addActivity.html', {'activityform': form})


@login_required
def activity_information(request, id):
    activity = get_object_or_404(ActivityModel, id=id)

    if request.method == "POST":

        actform = activity_form(request.POST, instance=activity)
        insform = InstructionForm(request.POST, request.FILES, instance=activity)
        if actform.is_valid():
            actform.save()
            return redirect('activityinformation', id)
        if insform.is_valid():
            # insform.save()
            tempins = instruction(pdf=request.FILES["pdf"], activity=activity)
            tempins.save()
            return redirect('activityinformation', id)


        # for qty in request.POST[required.pk]:
        #     print(qty)
        #     try:
        #         updatedvalue = get_object_or_404(ActivityPartModel, id=int(completed))
        #         updatedvalue.updateQuantity(int(request.POST[completed])
        #     except ValueError:
        #         pass

    required = ActivityPartModel.objects.filter(activity=id).filter(increment=False).order_by('order')
    for part in required:
        part.thumbnail = PartImageModel.objects.filter(part=part.part).first()
    produced = ActivityPartModel.objects.filter(activity=id).filter(increment=True).order_by('order')
    for part in produced:
        part.thumbnail = PartImageModel.objects.filter(part=part.part).first()

    instructions = instruction.objects.filter(activity=activity)
    instructionform = InstructionForm(initial={'activity': activity})

    form = activity_form(instance=activity)
    context = {'activityform': form,
               'activitypartsrequired': required,
               'activitypartsproduced': produced,
               'instructions': instructions,
               'instructionform': instructionform,
               'activity': activity,
               'history': ActivityPartModel.history.filter(activity=activity)
               }
    return render(request, 'ActivitiesApp/infoActivity.html', context)


@login_required
def add_required_part_to_activity(request, id, increment):
    activity = get_object_or_404(ActivityModel, id=id)
    activity_parts = ActivityPartModel.objects.filter(activity=id).filter(increment=increment)
    parts = PartModel.objects.all()
    form = required_part_form(initial={'activity': id, 'increment': increment})
    if increment == False:
        header = "Parts Required"
    else:
        header = "Parts Produced"
    context = {'activity': activity,
               'requiredpartform': form,
               'activityrequiredparts': activity_parts,
               'parts': parts,
               'header': header
               }

    if request.method == "POST":
        form = required_part_form(request.POST)
        if form.is_valid():
            form.save()
        return render(request, 'ActivitiesApp/addActivityPart.html', context)

    return render(request, 'ActivitiesApp/addActivityPart.html', context)


@require_POST
def save_new_ordering_parts_of_activity(request, id):
    form = PartOrderingForm(request.POST)

    if form.is_valid():
        ordered_ids = form.cleaned_data["ordering"].split(',')

        with transaction.atomic():
            current_order = 1
            for lookup_id in ordered_ids:
                group = ActivityPartModel.objects.get(id=lookup_id)
                group.order = current_order
                group.save()
                current_order += 1

    return redirect('activityinformation', id)


@login_required
def groups(request):
    # print(WorkCenterTypes.objects.filter(wcType=type))

    return render(request, 'ActivitiesApp/listGroups.html', {'header': 'GroupModel',
                                                             'groups': GroupModel.objects.all()})


@login_required
def add_group(request):
    if request.method == "POST":
        form = group_form(request.POST)

        if form.is_valid():
            form.save()
            return redirect('groups')

    else:
        form = group_form()
        return render(request, 'ActivitiesApp/addGroup.html', {'groupform': form})


@login_required
def group_information(request, id):
    group = get_object_or_404(GroupModel, id=id)
    activities = GroupActivityModel.objects.filter(group=id).values_list('activity', flat=True)
    parts = ActivityPartModel.objects.filter(activity__in=activities, increment=False)
    for part in parts:
        part.supplier = part.part.getPreferredSupplier()

    if request.method == "POST":
        form = group_form(request.POST, instance=group)
        if form.is_valid():
            form.save()
            return redirect('groups')

    else:
        form = group_form(instance=group)
        context = {'groupform': form,
                   'groupactivities': GroupActivityModel.objects.filter(group=id).order_by('order'),
                   'id': id,
                   'parts':parts}
        return render(request, 'ActivitiesApp/infoGroups.html', context)


class GroupActivityDelete(DeleteView):
    # http_method_names = ['post']
    model = GroupActivityModel
    fields = "__all__"

    def get_success_url(self):
        return reverse('groupinformation', args=[str(self.object.group.pk)])


@login_required
def add_required_activity_to_group(request, id):
    activities = ActivityModel.objects.all()
    group_activities = GroupActivityModel.objects.filter(group=id)
    group = get_object_or_404(GroupModel, id=id)

    form = required_activity_form(initial={'group': id, 'order': 100_000})
    context = {'requiredactivityform': form,
               'grouprequiredactivity': group_activities,
               'allactivities': activities,
               'id': id
               }
    if request.method == "POST":
        form = required_activity_form(request.POST)
        if form.is_valid():
            form.save()
        return render(request, 'ActivitiesApp/addGroupActivity.html', context)

    return render(request, 'ActivitiesApp/addGroupActivity.html', context)


class ActivityPartUpdate(UpdateView):
    http_method_names = ['post']
    model = ActivityPartModel
    fields = ['quantity', 'location']

    def form_valid(self, form):
        oldObject = ActivityPartModel.objects.get(id=self.object.id)
        change_reason = []
        if 'quantity' in form.changed_data:
            change_reason.append(f'quantity updated from {oldObject.quantity} to {self.object.quantity}')

        if 'location' in form.changed_data:
            change_reason.append(f'extra info amended from {oldObject.location} to {self.object.location}')

        superReturn = super().form_valid(form)
        update_change_reason(self.object, f'{",".join(change_reason)}')
        return superReturn

    def get_success_url(self):
        return reverse('activityinformation', args=[str(self.object.activity.pk)])


class ActivityPartDelete(DeleteView):
    http_method_names = ['post']
    model = ActivityPartModel

    def get_success_url(self):
        return reverse('activityinformation', args=[str(self.object.activity.pk)])


@require_POST
def save_new_ordering_activities_of_group(request, id):
    form = OrderingForm(request.POST)

    if form.is_valid():
        ordered_ids = form.cleaned_data["ordering"].split(',')

        with transaction.atomic():
            current_order = 1
            for lookup_id in ordered_ids:
                group = GroupActivityModel.objects.get(id=lookup_id)
                group.order = current_order
                group.save()
                current_order += 1

    return redirect('groupinformation', id)

# @login_required
# def work_center(request):
#
#     return render(request, 'listWorkCenters.html', {'header': 'GroupModel',
#                                                     'workcenters': GroupModel.objects.all(),
#                                                     'types': WorkCenterTypes.objects.all()})

# # use for getting all files in instruction model relating to job from ActivityModel model
# some_manual = Manual.objects.get(id=1)
# some_manual_pdfs = some_manual.manualpdf_set.all()

ActivitiesApp/templates/ActivitiesApp/addActivity.html
{% extends "includes/base.html" %}

{% load crispy_forms_tags %}

{% block body%}

<div class="container">
    <form method="POST">
        <br>
        {% csrf_token %}
        {% crispy activityform %}
    </form>
</div>

{% endblock %}

ActivitiesApp/templates/ActivitiesApp/addActivityPart.html
{% extends "includes/base.html" %}

{% load crispy_forms_tags %}

{% block body%}
<a href="{% url 'activities' %}" class="badge badge-light">Activities</a>>
<a href="{% url 'activityinformation' activity.pk %}" class="badge badge-light">{{ activity }}</a>
<br>

<div class="row">
    <div class="col-sm">
        <p class="font-weight-bold">{{ header }}</p>
        <br>
        <br>
        <form class="form-inline">
            <input class="form-control" type="text" id="searchBar" onkeyup="search()" placeholder="Search" aria-label="Search">
        </form>
        <br>
        <table class="table table-hover" id="selection">
            <thead>
            <tr>
                <th>Part Number</th>
                <th>Description</th>

            </tr>
            </thead>
            <tbody>
            {% for part in parts %}
            <tr data-id="{{ part.id }}">
                <td>{{ part.partNumber }}</td>
                <td>{{ part.description }}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="col-sm">
        <div class="container">
            <form method="POST">
                {% csrf_token %}
                {% crispy requiredpartform %}
            </form>
        </div>
        <table class="table table-hover">
            <tbody>
            {% for required in activityrequiredparts %}
            <tr data-href="{% url 'info_part' required.part.id %}">
                <td>{{ required.part.partNumber }}</td>
                <td>{{ required.part.description }}</td>
                <td>{{ required.quantity }}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

ActivitiesApp/templates/ActivitiesApp/addGroup.html
{% extends "includes/base.html" %}

{% load crispy_forms_tags %}

{% block body %}

<div class="container-fluid">
    <div class="row">
        <div class="col-sm">
            <form method="POST">
                <br>
                {% csrf_token %}
                {% crispy groupform %}
            </form>
        </div>
    </div>
</div>

{% endblock %}

ActivitiesApp/templates/ActivitiesApp/addGroupActivity.html
{% extends "includes/base.html" %}

{% load crispy_forms_tags %}

{% block body%}
<a href="{% url 'groups' %}" class="badge badge-light">Groups</a>>
<a href="{% url 'groupinformation' id %}" class="badge badge-light">{{ grouprequiredactivity.first.group.groupName }}</a>

<br>

<div class="row">
    <div class="col-sm">
        <p class="font-weight-bold">Add Activity to Group</p>
        <br>
        <form class="form-inline">
            <input class="form-control" type="text" id="searchBar" onkeyup="search()" placeholder="Search" aria-label="Search">
        </form>
        <br>
        <table class="table table-hover" id="selection">
            <thead>
            <tr>
                <th>Activity Name</th>
            </tr>
            </thead>
            <tbody>
            {% for activity in allactivities %}
            <tr data-aid="{{ activity.id }}">
                <td>{{ activity.activityName }}</td>
                <td>{{ activity.description }}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="col-sm">
        <div class="container">
            <form method="POST">
                {% csrf_token %}
                {% crispy requiredactivityform %}
            </form>
        </div>
        <table class="table table-hover">
            <tbody>
            {% for activity in grouprequiredactivity %}
            <tr data-href="{% url 'activityinformation' activity.activity.id %}">
                <td>{{ activity.activity.activityName }}</td>
                <td>{{ activity.activity.description }}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
        <br>
    </div>
</div>


{% endblock %}

ActivitiesApp/templates/ActivitiesApp/infoActivity.html
{% extends "includes/base.html" %}

{% load crispy_forms_tags %}

{% block body %}
<a href="{% url 'activities' %}" class="badge badge-light">Activities</a>
<br>
<p class="font-weight-bold">{{ activity.activityName }}</p>
<ul class="nav nav-tabs">
    <li><a class="nav-link active" data-toggle="tab" href="#information">Activity Information</a></li>
    <li><a class="nav-link" data-toggle="tab" href="#parts">Activity Parts</a></li>
    <li><a class="nav-link" data-toggle="tab" href="#history">Activity History</a></li>
</ul>
<div class="tab-content">
    <div id="information" class="tab-pane active">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm">
                    <form method="POST">
                        <br>
                        {% csrf_token %}
                        {% crispy activityform %}
                    </form>
                </div>
            </div>
            <div class="row" style="min-height: 800px;">
                {% for instruction in instructions %}
                <iframe src='{{ instruction.pdf.url }}#toolbar=0' width="100%" height="800px"></iframe>
                {% endfor %}
                <br>
                <form enctype="multipart/form-data" method="post">
                    {% csrf_token %}
                    {{ instructionform.as_p }}
                    <button type="submit">Upload</button>
                </form>

            </div>
        </div>
    </div>
    <div id="parts" class="tab-pane">
        <div class="row" style="min-height: 700px;">
            <div class="col-sm">
                <div class="my-custom-scrollbar table-wrapper-scroll-y" style="max-height: 670px;">
                    <b>Parts Required</b>
                    <form class="orderingForm" data-tblid="requiredTbl" data-btnid="requiredBtn" method="post"
                          action="{% url 'save-part-ordering' activity.id %}">
                        {% csrf_token %}
                        <input type="hidden" class="orderingInput" name="ordering">
                        <button id="requiredBtn" class="btn btn-outline-primary btn-lg float-right mr-2" disabled>
                            Save
                            ordering - Required
                        </button>
                    </form>
                    <table class="table table-hover">
                        <thead>
                        <tr>
                            <th></th>
                            <th>Image</th>
                            <th>Part Number</th>
                            <th>Description</th>
                            <th>Quantity</th>
                            {% if required.activity.workCenter.name == "Picking" or "Hose Cutting" %}
                            <th>Extra Information</th>
                            {% endif %}
                        </tr>
                        </thead>
                        <tbody id="requiredTbl">
                        {% for required in activitypartsrequired %}
                        <tr data-lookup="{{ required.pk }}">
                            <td><span class="handle"></span></td>
                            <td><img src="{{ required.thumbnail.image.url }}"
                                     style="height: 100px;"/></td>
                            <td data-href="{% url 'info_part' required.part.id %}">{{ required.part.partNumber }}
                            </td>
                            <td data-href="{% url 'info_part' required.part.id %}">{{ required.part.description }}
                            </td>
                            <form class="silent_form" method="POST" action="{% url 'editactivitypart' required.pk %}">
                                <td>
                                    {% csrf_token %}
                                    <input class="md-2" type="number" value="{{ required.quantity }}"
                                           name="quantity"
                                           id="id_quantity">
                                </td>
                                {% if required.activity.workCenter.name == "Picking" or "Hose Cutting" %}
                                <td>
                                    <input value="{{ required.location }}" name="location"
                                           id="id_location">
                                </td>
                                {% endif %}
                                <td><input type="submit" class="btn btn-primary" value="Update"></td>
                            </form>
                            <form action="{% url 'deleteactivitypart' required.pk %}" method="post"
                                  style="display: inline;">
                                <td>
                                    {% csrf_token %}
                                    <input type="submit" class="btn btn-danger" value="Delete"
                                           onclick="return confirm('Are you sure you want to delete {{ required.part.partNumber }} from {{ activity.activityName }}?');">
                                </td>
                            </form>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div style="position: absolute; bottom: 0;">
                    <a href="{% url 'addrequired' activity.id %}" class="btn btn-secondary btn-sm btn-pad"
                       role="button">Add Required
                        Part</a>
                </div>

            </div>
            <div class="col-sm">
                <div class="my-custom-scrollbar table-wrapper-scroll-y" style="height: 670px;">
                    <b>Parts Produced</b>
                    <form class="orderingForm" data-tblid="producedTbl" data-btnid="producedOrder" method="post"
                          action="{% url 'save-part-ordering' activity.id %}">
                        {% csrf_token %}
                        <input type="hidden" class="orderingInput" name="ordering">
                        <button id="producedOrder" class="btn btn-outline-primary btn-lg float-right mr-2" disabled>
                            Save
                            ordering - Produced
                        </button>
                    </form>
                    <table class="table table-hover">
                        <thead>
                        <tr>
                            <th></th>
                            <th>Image</th>
                            <th>Part Number</th>
                            <th>Description</th>
                            <th>Quantity</th>
                            {% if produced.activity.workCenter.name == "Picking" or "Hose Cutting" %}
                            <th>Extra Information</th>
                            {% endif %}
                        </tr>
                        </thead>
                        <tbody id="producedTbl">
                        {% for produced in activitypartsproduced %}
                        <tr data-lookup="{{ produced.pk }}">
                            <td><span class="handle"></span></td>
                            <td><img class="img-responsive" src="{{ produced.thumbnail.image.url }}"
                                     style="height: 100px"/></td>
                            <td data-href="{% url 'info_part' produced.part.id %}">{{ produced.part.partNumber }}
                            </td>
                            <td data-href="{% url 'info_part' produced.part.id %}">{{ produced.part.description }}
                            </td>
                            <form class="silent_form" method="POST" action="{% url 'editactivitypart' produced.pk %}">
                                <td>
                                    {% csrf_token %}
                                    <input type="number" value="{{ produced.quantity }}" name="quantity"
                                           id="id_quantity">
                                </td>
                                {% if produced.activity.workCenter.name == "Picking" or "Hose Cutting" %}
                                <td>
                                    <input value="{{ produced.location }}" name="location"
                                           id="id_location">
                                </td>
                                {% endif %}
                                <td><input type="submit" class="btn btn-primary" value="Update"></td>
                            </form>
                            <form action="{% url 'deleteactivitypart' produced.pk %}" method="post"
                                  style="display: inline;">
                                <td>
                                    {% csrf_token %}
                                    <input type="submit" class="btn btn-danger" value="Delete"
                                           onclick="return confirm('Are you sure you want to delete {{ produced.part.partNumber }} from {{ activity.activityName }}?');">
                                </td>
                            </form>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div style="position: absolute; bottom: 0;">
                    <a href="{% url 'addproduced' activity.id %}" class="btn btn-secondary btn-sm btn-pad"
                       role="button">Add Produced
                        Part</a>
                </div>
            </div>
        </div>
        <input class="btn btn-secondary btn-sm" id="submit-id-save" type="submit" value="Update Quantities">
    </div>
    <div id="history" class="tab-pane">
        <table class="table table-hover" id="selection">
            <thead>
            <tr>
                <th>Part Number</th>
                <th>Description</th>
                <th>User</th>
                <th>Time</th>
                <th>Quantity</th>
                <th>Extra info</th>
                <th>Change Reason</th>

            </tr>
            </thead>

            <tbody>

            {% for part in history %}

            <tr data-href="{% url 'info_part' part.id %}"
                {% if part.obsolete %} class="table-dark" {% endif %}
                {% if part.low %} class="table-danger" {% endif %}>
                <td>{{ part.part.partNumber }}</td>
                <td>{{ part.part.description }}</td>
                <td>{{ part.history_user }}</td>
                <td>{{ part.history_date }}</td>
                <td>{{ part.quantity }}</td>
                <td>{{ part.location }}</td>
                <td>{{ part.history_change_reason }}</td>
            </tr>

            {% endfor %}

            </tbody>

        </table>
    </div>
</div>

{% endblock %}

ActivitiesApp/templates/ActivitiesApp/listActivities.html
{% extends "includes/base.html" %}

{% block body %}
<br>
<div class="container-fluid">
    <a href="{% url 'addactivity' %}" class="btn btn-secondary btn-sm btn-pad" role="button">New Activity</a>
</div>
<br>
<form class="form-inline">
    <input class="form-control" type="text" id="searchBar" onkeyup="search()" placeholder="Search" aria-label="Search">
</form>
<br>
<table class="table table-hover" id="selection">
    <thead>
    <tr>
        <th>Activity</th>
    </tr>
    </thead>

    <tbody>

    {% for activity in activities %}

    <tr data-href="{% url 'activityinformation' activity.id %}">
        <td>{{ activity.activityName }}</td>
        <td>{{ activity.description }}</td>
        <td>{{ activity.workCenter.name }}</td>
    </tr>

    {% endfor %}

    </tbody>

</table>

{% endblock %}

ActivitiesApp/templates/ActivitiesApp/listGroups.html
{% extends "includes/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block body %}


{% for type in types %}
<a href="{% url 'groups' type.id %}" class="btn btn-secondary btn-sm btn-pad" role="button">{{ type.description }}</a>
{% endfor %}
<br>
<br>
<form class="form-inline my-2 my-lg-0">
    <input class="form-control mr-sm-2" type="text" id="searchBar" onkeyup="search()" placeholder="Search"
           aria-label="Search">
</form>
<form method="POST">
    <br>

</form>
<br>

<div class="container-fluid">
    <a href="{% url 'addgroup' %}" class="btn btn-secondary btn-sm btn-pad" role="button">New Group</a>
</div>

<br>

<table class="table table-hover" id="selection">
    <thead>
    <tr>
        <th>Groups</th>
    </tr>
    </thead>
    <tbody>
    {% for group in groups %}
    <tr data-href="{% url 'groupinformation' group.id %}">
        <td>{{ group.groupName }}</td>
        <td>{{ group.workCenter }}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>

{% endblock %}